### PR TITLE
About dialog implementation

### PR DESCRIPTION
**Pull request by danielsanfr**
Here is my implementation of AboutDialog.

This second commit, only to self destroy the dialog when it is not visible for some time (5 minutes). I know that the gain in memory is little, but do not believe that the user will be looking at this dialogue constantly.

### CODE REVIEW

**Comment by nathan-osman** [comment]
Thanks for doing this! I'll get it merged tomorrow morning since it's almost midnight here.

Just a quick question - wouldn't it be easier to show the dialog as a modal dialog box using `QDialog::exec()` instead of `show()`? Then we could do this:

    AboutDialog().exec();

The call wouldn't return until the dialog box was closed and we wouldn't need to keep a pointer to it.

**Comment by danielsanfr** [comment]
I fully agree with you.

As this dialog is very simple, and only seen a few times, really it's okay to do that way.

A more general question: Do you think all the dialogues should be shown in this way? (I'm asking this, already wondering how I should like to proceed with the settings dialog.)

**Comment by nathan-osman** [comment]
Yes, please use the same method for the settings dialog. The only window that doesn't need to work this way is the transfer window (which isn't a dialog box anyway).

**Comment by nathan-osman** [comment]
...and merged! Thanks for doing this. I really like the design of the dialog.

**Comment by danielsanfr** [comment]
Thank you :+1: !

I liked how you changed the name of slot from `onCreditsOrLicenceChecked` to `toggleTextBrowser`. But just like to give a little hint. Usually when a slot will only react to a signal, the default Qt is to use the `on` in front of the slot name. Then we could do this:

```c++
void onToggleTextBrowser(bool checked);
```

And I forgot to make the buttons connection directly by file `.ui`, sorry.

**Comment by nathan-osman** [comment]
Oh, okay. Thanks for the tip.

**Pull request merged**
