### PR TITLE
Added Italian translation.

### PR DESCRIPTION
**Pull request by gneb962**

### CODE REVIEW

**Comment by gneb962** [comment]
I'm Max, I mailed you days ago. Managed to create the translation with Qt Lingust and to learn some git basics !

**Comment by nathan-osman** [comment]
Wow, thanks! Great job. I'll get this merged as soon as I get home tomorrow.

**Comment by nathan-osman** [comment]
Thanks again! I've merged the translation into the `master` branch to be included in the next release. Would it be alright if I give you credit in the About dialog under the list of translators? If so, please let me know how you'd like your name to appear.

**Comment by gneb962** [comment]
Great!
Yea, a credit would be nice, thanks :D
Just put "Massimo Bertoli" !

**Pull request merged**
